const baseUrl = process.env.REACT_APP_IMG_URL;

export const products = [
  {
    id: 1,
    name: "Mathematics - X CBSE",
    price: "26,250",
    // image: "https://dhruv-kundu14.github.io/drona_learning/Icons/Ecom/books/1.png",
    image: `${baseUrl}/Icons/Ecom/books/1.png`,
    description: "Advanced Plan - ASLP",
    course: "ASLP",
    type: "Advanced",
    originalPrice: "35,000",
    overview:
      "The MATHEMATICS - X CBSE : Advanced Plan - ASLP is the definitive worksheet-based course along with Live Interactive Session once a week for reinforcement /reinforcement and doubt clarification  designed to excel in CBSE X Examination. With comprehensive chapter-wise worksheets, test papers,  correction and feedback by expert teachers ,reinforcement of the concept during the live interactive class  students develop a solid grasp of mathematical  concepts. This course includes continuous study plan under  expert guidance, ensuring students master the curriculum while fostering a genuine interest in Mathematics .",
  },
  {
    id: 2,
    name: "CBSE X : Mathematics",
    price: "2,500",
    // image:  "https://dhruv-kundu14.github.io/drona_learning/Icons/Ecom/books/2.png",
    image: `${baseUrl}/Icons/Ecom/books/2.png`,
    description: "Test Series Standard Plan",
    course: "Test Series",
    type: "Standard",
    originalPrice: "3,500",
    overview:
      "Welcome to Test Series Package, a valuable tool for students preparing for CBSE Examinations 2025 to measure their progress and lead towards perfection. The test series comes with detailed feedback on students’ performance This information can help them to focus on the areas they need improvement. This course is without a doubt the most comprehensive Mathematics grade X  course available either offline or online. We have no doubt that on enrolment of  this course, the student will immensely benefit.",
  },
  {
    id: 3,
    name: "CBSE X : Mathematics",
    price: "5,100",
    // image: "https://dhruv-kundu14.github.io/drona_learning/Icons/Ecom/books/3.png",
    image: `${baseUrl}/Icons/Ecom/books/3.png`,
    description: "Test Series Advanced Plan",
    course: "Test Series",
    type: "Advanced",
    originalPrice: "6,100",
    overview: "",
  },
  {
    id: 4,
    name: "CBSE X : Science",
    price: "5,100",
    // image: "https://dhruv-kundu14.github.io/drona_learning/Icons/Ecom/books/4.png",
    image: `${baseUrl}/Icons/Ecom/books/4.png`,
    description: "Test Series Advanced Plan",
    course: "Test Series",
    type: "Advanced",
    originalPrice: "6,100",
    overview: "",
  },
  {
    id: 5,
    name: "CBSE X : Science",
    price: "2,500",
    // image: "https://dhruv-kundu14.github.io/drona_learning/Icons/Ecom/books/5.png",
    image: `${baseUrl}/Icons/Ecom/books/5.png`,
    description: "Test Series Standard Plan",
    course: "Test Series",
    type: "Standard",
    originalPrice: "3,500",
    overview: "",
  },
  {
    id: 6,
    name: "Science - X CBSE",
    price: "8,999",
    // image: "https://dhruv-kundu14.github.io/drona_learning/Icons/Ecom/books/6.png",
    image: `${baseUrl}/Icons/Ecom/books/6.png`,
    description: "Standard Plan - ASLP",
    course: "ASLP",
    type: "Standard",
    originalPrice: "9,999",
    overview:
      "The Science - X CBSE: Standard Plan - ASLP is the definitive worksheet-based course designed to excel in CBSE Class X Science. With comprehensive chapter-wise worksheets, additional test papers, and expert feedback, students develop a solid grasp of scientific concepts. This course integrates interactive sessions, continuous updates, and expert guidance, ensuring students master the curriculum while fostering a genuine interest in science.",
  },
  {
    id: 7,
    name: "Science - X CBSE",
    price: "11,999",
    // image: "https://dhruv-kundu14.github.io/drona_learning/Icons/Ecom/books/7.png",
    image: `${baseUrl}/Icons/Ecom/books/7.png`,
    description: "Advanced Plan - ASLP",
    course: "ASLP",
    type: "Advanced",
    originalPrice: "12,999",
    overview: "",
  },
  {
    id: 8,
    name: "Mathematics - X ICSE",
    price: "8,999",
    // image: "https://dhruv-kundu14.github.io/drona_learning/Icons/Ecom/books/8.png",
    image: `${baseUrl}/Icons/Ecom/books/8.png`,
    description: "Standard Plan - ASLP",
    course: "ASLP",
    type: "Standard",
    originalPrice: "9,999",
    overview: "",
  },
  {
    id: 9,
    name: "Mathematics - X ICSE",
    price: "11,999",
    // image: "https://dhruv-kundu14.github.io/drona_learning/Icons/Ecom/books/9.png",
    image: `${baseUrl}/Icons/Ecom/books/9.png`,
    description: "Advanced Plan - ASLP",
    course: "ASLP",
    type: "Advanced",
    originalPrice: "12,999",
    overview: "",
  },
  {
    id: 10,
    name: "Mathematics - X CBSE",
    price: "6,999",
    // image: "https://dhruv-kundu14.github.io/drona_learning/Icons/Ecom/books/10.png",
    image: `${baseUrl}/Icons/Ecom/books/10.png`,
    description: "Standard Plan - ASLP",
    course: "ASLP",
    type: "Standard",
    originalPrice: "7,999",
    overview: "",
  },
  {
    id: 11,
    name: "Science - IX",
    price: "8,999",
    // image: "https://dhruv-kundu14.github.io/drona_learning/Icons/Ecom/books/11.png",
    image: `${baseUrl}/Icons/Ecom/books/11.png`,
    description: "Advanced Plan - ASLP",
    course: "ASLP",
    type: "Advanced",
    originalPrice: "9,999",
    overview: "",
  },
  {
    id: 12,
    name: "Science - IX",
    price: "4,999",
    // image: "https://dhruv-kundu14.github.io/drona_learning/Icons/Ecom/books/12.png",
    image: `${baseUrl}/Icons/Ecom/books/12.png`,
    description: "Standard Plan - ASLP",
    course: "ASLP",
    type: "Standard",
    originalPrice: "5,999",
    overview: "",
  },
  {
    id: 13,
    name: "Science - VIII",
    price: "4,999",
    // image: "https://dhruv-kundu14.github.io/drona_learning/Icons/Ecom/books/13.png",
    image: `${baseUrl}/Icons/Ecom/books/13.png`,
    description: "Standard Plan - ASLP",
    course: "ASLP",
    type: "Standard",
    originalPrice: "5,999",
    overview: "",
  },
  {
    id: 14,
    name: "Science - VIII",
    price: "7,999",
    // image: "https://dhruv-kundu14.github.io/drona_learning/Icons/Ecom/books/14.png",
    image: `${baseUrl}/Icons/Ecom/books/14.png`,
    description: "Advanced Plan - ASLP",
    course: "ASLP",
    type: "Advanced",
    originalPrice: "8,999",
    overview: "",
  },
  {
    id: 15,
    name: "Mathematics - VIII",
    price: "9,999",
    // image: "https://dhruv-kundu14.github.io/drona_learning/Icons/Ecom/books/15.png",
    image: `${baseUrl}/Icons/Ecom/books/15.png`,
    description: "Advanced Plan - ASLP",
    course: "ASLP",
    type: "Advanced",
    originalPrice: "10,999",
    overview: "",
  },
  {
    id: 16,
    name: "Mathematics - VIII",
    price: "6,999",
    // image: "https://dhruv-kundu14.github.io/drona_learning/Icons/Ecom/books/16.png",
    image: `${baseUrl}/Icons/Ecom/books/16.png`,
    description: "Standard Plan - ASLP",
    course: "ASLP",
    type: "Standard",
    originalPrice: "7,999",
    overview: "",
  },
  {
    id: 17,
    name: "Mathematics - VII",
    price: "9,999",
    // image: "https://dhruv-kundu14.github.io/drona_learning/Icons/Ecom/books/17.png",
    image: `${baseUrl}/Icons/Ecom/books/17.png`,
    description: "Advanced Plan - ASLP",
    course: "ASLP",
    type: "Advanced",
    originalPrice: "10,999",
    overview: "",
  },
  {
    id: 18,
    name: "Science - VII",
    price: "7,999",
    // image: "https://dhruv-kundu14.github.io/drona_learning/Icons/Ecom/books/18.png",
    image: `${baseUrl}/Icons/Ecom/books/18.png`,
    description: "Advanced Plan - ASLP",
    course: "ASLP",
    type: "Advanced",
    originalPrice: "8,999",
    overview: "",
  },
  {
    id: 19,
    name: "Mathematics - VI",
    price: "9,999",
    // image: "https://dhruv-kundu14.github.io/drona_learning/Icons/Ecom/books/19.png",
    image: `${baseUrl}/Icons/Ecom/books/19.png`,
    description: "Advanced Plan - ASLP",
    course: "ASLP",
    type: "Advanced",
    originalPrice: "10,999",
    overview: "",
  },
  {
    id: 20,
    name: "Science - VII",
    price: "4,999",
    // image: "https://dhruv-kundu14.github.io/drona_learning/Icons/Ecom/books/20.png",
    image: `${baseUrl}/Icons/Ecom/books/20.png`,
    description: "Standard Plan - ASLP",
    course: "ASLP",
    type: "Standard",
    originalPrice: "5,999",
    overview: "",
  },
  {
    id: 21,
    name: "Mathematics - VII",
    price: "6,999",
    // image: "https://dhruv-kundu14.github.io/drona_learning/Icons/Ecom/books/21.png",
    image: `${baseUrl}/Icons/Ecom/books/21.png`,
    description: "Standard Plan - ASLP",
    course: "ASLP",
    type: "Standard",
    originalPrice: "7,999",
    overview: "",
  },
  {
    id: 22,
    name: "Mathematics - VI",
    price: "6,999",
    // image: "https://dhruv-kundu14.github.io/drona_learning/Icons/Ecom/books/22.png",
    image: `${baseUrl}/Icons/Ecom/books/22.png`,
    description: "Standard Plan - ASLP",
    course: "ASLP",
    type: "Standard",
    originalPrice: "7,999",
    overview: "",
  },
];
